### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by ghost** [OpenNLPhub/CBT4Rel#1]
您好！非常感谢您分享代码，我最近也在用pytorch复现这篇文章，您的代码给了我很大的启发。

但是我的代码测试的时候F1值只有60左右，远远达不到Keras版本代码的性能，不知您是否解决了End2End性能的问题？

**Comment by Zrealshadow** [comment]
我复现的实验中也远远没有达到论文展示的水平，我测试的数据集是WebNLG, 原论文中达到了91% 我的只有58% QAQ.
 我有点懒，没有去提点了。

对于F1 性能问题，我说说我的看法（也没认真研究过），只能作为参考
- bert 预训练集选取，我直接选的bert-base-uncased, 不知道原作者实验取得什么（当然他没加载预训练集也比我高得多233）
- 随机种子选取， 这就是玄学问题了，在我的代码里面没有重新定义随机种子，对model进行随机初始化
- 论文中有一个 全局语义向量 + subject 语义向量 的操作，这里我和源码实现的不相同， 原作者使用头尾指针所指单词的词向量加权求和， 我是使用整个subject所有单词的词向量加权求和。
- 最后两个我觉得最重要
     - 解码，我的解码是自己写的，没有参照原码中的解码，我看原论文源码issue中，好像对于解码方式有争议，没仔细看，你可以按照源码解码的思路对结果进行解码。
     - 过拟合，我的源码中没啥dropout层，而且训练了100epoch，可能过拟合了 23333

上面是我的建议哈 ！

**Comment by ghost** [comment]
万分感谢！
