### ISSUE TITLE
The result is inconsistent with the original code

### ISSUE THREAD

**Issue by YuqiChen4188** [OpenNLPhub/CBT4Rel#2]
Is there any solution to this problem?

**Comment by Zrealshadow** [comment]
Overwrite the decoding method.

In this code, the decoding method is not serious. I did not finish it with the reference to the original Keras code.

The decoding algorithmn of this code is to change a batch result to a start label vector and a end label vector, than match couple of start and end label One by One. It means that if one label is wrong, it will lead subsequent series of mistakes.
This can explain why the binary classifier have high F1-score, but extracting relation failed. I hope you can understand what i mean.

**Comment by YuqiChen4188** [comment]
thanks for your  explanation
